### ISSUE TITLE
Source conferences from database

### ISSUE THREAD

**Issue by programmiri** [conference-buddy/conference-buddy-web-app#25]
### Discussed in https://github.com/conference-buddy/conference-buddy-web-app/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **programmiri** December 22, 2021</sup>
- conferences now are a table in supabase
- conference pages and conference list should be sourced from supabase instead of markdown files</div>

**Comment by coderbyheart** [comment]
Is there a way for you to share the schema and seed data for supabase, so developers can have their own instance running?

**Comment by programmiri** [comment]
@coderbyheart  will look into that!
